# Generated by Django 4.2.1 on 2023-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_yt', models.URLField(max_length=1000)),
                ('points', models.IntegerField(default=0, max_length=1000)),
                ('html_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
